import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Preserve existing category labels and landing pages while grouping by language.
function existingCategory(dirName: string) {
  const metadata = JSON.parse(
    readFileSync(join(__dirname, 'docs', dirName, '_category_.json'), 'utf8'),
  );
  return {
    type: 'category' as const,
    label: metadata.label,
    link: metadata.link,
    items: [{type: 'autogenerated' as const, dirName}],
  };
}

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'overview',
    {
      type: 'category',
      label: 'KDB/Q',
      link: {type: 'doc', id: 'intro'},
      items: [
        'intro',
        existingCategory('studyPlan'),
        existingCategory('language'),
        existingCategory('architecture'),
        existingCategory('concepts'),
        existingCategory('codingPractice'),
        existingCategory('tutorials'),
      ],
    },
    {
      type: 'category',
      label: 'PeachQ',
      link: {type: 'doc', id: 'peachq/intro'},
      items: [{type: 'autogenerated', dirName: 'peachq'}],
    },
    existingCategory('productivity'),
  ],
};

export default sidebars;
